import Script from 'next/script';

export default function Head() {
  return (
    <>
      <title>Travel Advisor</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <Script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=geometry,drawing,places&key=AIzaSyBUoBRAhpgOG3zD6_gtBqUBNqmZRP1MEik"></Script>
    </>
  )
}
